<?php
namespace Kma\Component\Survey\Administrator\View\Logs;

defined('_JEXEC') or die;

use Kma\Library\Kma\View\LogsHtmlView;

class HtmlView extends LogsHtmlView
{
	public function display($tpl = null)
	{
		parent::display($tpl); // TODO: Change the autogenerated stub
	}

	protected function init(): void
	{
		parent::init();

		//Load scripts and styles
		$this->wa->useScript('select2.script');
		$this->wa->useStyle('select2.style');
		$this->wa->useScript('com_survey.script');
		$this->wa->useStyle('com_survey.style');
	}

}