<?php
namespace Kma\Component\Eqa\Administrator\Base;
defined('_JEXEC') or die();

use Joomla\CMS\Access\Rules;
use Joomla\CMS\Table\Table;
use Joomla\Database\DatabaseDriver;
use JTable;
use Kma\Component\Eqa\Administrator\Helper\GeneralHelper;
use Kma\Component\Eqa\Administrator\Helper\StringHelper;

class EqaTable extends Table{
	protected string $itemName;
    public function __construct(DatabaseDriver $db, string $tableName='', string $keyName='')
    {
	    $className = get_class($this);
	    $shortClassName = basename(str_replace('\\', '/', $className));
	    $this->itemName = substr($shortClassName,0,strlen($shortClassName)-5); //strlen('Table') = 5
        if(empty($tableName)){
            $items = StringHelper::convertSingleToPlural($this->itemName);
            $tableName = '#__eqa_'.strtolower($items);
        }
        if(empty($keyName))
            $keyName='id';
        parent::__construct($tableName,$keyName, $db);
    }

	protected function _getAssetName(): string
	{
		return 'com_eqa.' . $this->itemName . '.' . $this->_tbl_key;
	}

	protected function _getAssetTitle(): string
	{
		return $this->_getAssetName();
	}

	/**
	 * @throws \Exception
	 */
	protected function _getAssetParentId(?Table $table = null, $id = null)
	{
		/**
		 * 1. Tạo một instance của bảng AssetTable (bảng #__assets)
		 * 2. Lấy bản ghi có tên (`name`) là 'com_eqa'
		 * 3. Trả về id của bản ghi đó
		 */
		$mvc = GeneralHelper::getMVCFactory();
		$assetTable = $mvc->createTable('Asset');
		$component = $assetTable->loadByName('com_eqa');
		if($component)
			return $component->id;
		return $assetTable->getRootId();
	}

	public function bind($src, $ignore = [])
	{
		if(isset($array['rules']) && is_array($array['rules'])){
			$this->setRules($array['rules']);
		}
		return parent::bind($src, $ignore); // TODO: Change the autogenerated stub
	}
}